### ISSUE TITLE
NPE in extractFromDependencyParse

### ISSUE THREAD

**Issue by saraswat** [mmessmer/glueSemWorkbench#12]
(Running from the directory (not the jar file) -- but no changes made in source.)

```
 java -cp "$CORENLP_HOME/*:./src" main.WorkbenchMain  -dp
The Glue Semantics Workbench
copyright 2018 Moritz Messmer & Mark-Matthias Zymla

Current settings: automatic beta reduction: on		output mode: plain
Starting interactive dependency mode...

Enter sentence to be analyzed or enter 'quit' to exit the program.
Ann reported earnings.
[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
[nsubj(reported-2, Ann-1), root(ROOT-0, reported-2), dobj(reported-2, earnings-3)]
Ann/NNP This is a subject
Exception in thread "main" java.lang.NullPointerException
	at glueSemantics.synInterface.dependency.SentenceMeaning.extractFromDependencyParse(SentenceMeaning.java:141)
	at glueSemantics.synInterface.dependency.SentenceMeaning.<init>(SentenceMeaning.java:48)
	at main.WorkbenchMain.initiateDependencyMode(WorkbenchMain.java:126)
	at main.WorkbenchMain.main(WorkbenchMain.java:74)
bash-3.2$ 

```

**Comment by saraswat** [comment]
This is because `extractFronDependencyParse.extractArgumentEntries` only deals with`NN` and `NNS` for now -- it needs to be able to handle `NNP`, `DT`, `PRS` etc.
