### ISSUE TITLE
Exception on Subj Verb Obj sentence.

### ISSUE THREAD

**Issue by saraswat** [mmessmer/glueSemWorkbench#5]
I compiled the code (with Stanford jars), and am able to get a response for `John smiles`.

(a) `John smiles`:  works!
```
[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.3 sec].
[nsubj(smiles-2, John-1), root(ROOT-0, smiles-2)]
John/NNP This is a subject
smiles/VBZ has arity 1
[g : j[0], (g ⊸ f) : λx_e.smiles(x)[1]] => null
Searching for valid proofs...
Agenda: [g : j[0], (g ⊸ f) : λx_e.smiles(x)[1]]
Combining premises (g ⊸ f) : λx_e.smiles(x)[1] and g : j[0]
-->f : smiles(j)[0, 1]
Found valid deduction(s): 
f : smiles(j)[0, 1]
Done!
```
Awesome!

However, various other simple examples produce exceptions:

(b) `Hello, world!` : Here the exception seems informational, so this is probably ok (not a bug). (Though the error message is a bit odd `No valid proof found for premises` ... maybe `No meaning conclusion can be derived from premises`?)

```
Enter sentence to be analyzed or enter 'quit' to exit the program.
Hello, World!
[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
[discourse(World-3, Hello-1), root(ROOT-0, World-3)]
World/NNP has arity 0
[] => null
Searching for valid proofs...
Agenda: []
prover.ProverException: No valid proof found for premises
	at prover.LLProver.deduce(LLProver.java:164)
	at Main.searchProof(Main.java:114)
	at Main.initiateDependencyMode(Main.java:90)
	at Main.main(Main.java:45)
Done!
```

(c) `Bill loves Hillary.`: this seems more problematic

```
Enter sentence to be analyzed or enter 'quit' to exit the program.
Bill loves Hillary.
[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.3 sec].
[nsubj(loves-2, Bill-1), root(ROOT-0, loves-2), dobj(loves-2, Hillary-3)]
Bill/NNP This is a subject
Hillary/NNP This is an object
Exception in thread "main" java.lang.NullPointerException
	at glueSemantics.lexicon.Determiner.getScope(Determiner.java:161)
	at glueSemantics.lexicon.Verb.<init>(Verb.java:84)
	at glueSemantics.synInterface.dependency.SentenceMeaning.extractFromDependencyParse(SentenceMeaning.java:165)
	at glueSemantics.synInterface.dependency.SentenceMeaning.<init>(SentenceMeaning.java:46)
	at Main.initiateDependencyMode(Main.java:90)
	at Main.main(Main.java:45)
```
Note, the program exited after this traceback.

(d) `The cat jumped over the quick, brown fox.`: also this.

```
Enter sentence to be analyzed or enter 'quit' to exit the program.
The cat jumped over the lazy, brown fox.

[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.5 sec].
[det(cat-2, The-1), nsubj(jumped-3, cat-2), root(ROOT-0, jumped-3), case(fox-9, over-4), det(fox-9, the-5), amod(fox-9, lazy-6), amod(fox-9, brown-8), nmod(jumped-3, fox-9)]
glueSemantics.synInterface.dependency.LexicalParserException: Unknown determiner: the
	at glueSemantics.lexicon.Determiner.<init>(Determiner.java:147)
	at glueSemantics.synInterface.dependency.SentenceMeaning.extractArgumentEntries(SentenceMeaning.java:280)
	at glueSemantics.synInterface.dependency.SentenceMeaning.extractFromDependencyParse(SentenceMeaning.java:111)
	at glueSemantics.synInterface.dependency.SentenceMeaning.<init>(SentenceMeaning.java:46)
	at Main.initiateDependencyMode(Main.java:90)
	at Main.main(Main.java:45)
```

**Comment by mmessmer** [comment]
Thanks for the input. All of the mentioned issues were resolved in the most recent update.
