### ISSUE TITLE
Traceback on quantifier in object

### ISSUE THREAD

**Issue by saraswat** [mmessmer/glueSemWorkbench#8]
```
John loves every dog.
[main] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.2 sec].
[nsubj(loves-2, John-1), root(ROOT-0, loves-2), det(dog-4, every-3), dobj(loves-2, dog-4)]
John/NNP This is a subject
dog/NN This is an object
loves/VBZ has arity 2
[g : j[0], (h ⊸ h) : λy_e.dog(y)[1], ((h ⊸ h) ⊸ ((i ⊸ Y) ⊸ Y)) : λP_<e,t>.λQ_<e,t>.∀x[P(x) → Q(x)][2], (h ⊸ (h ⊸ f)) : λz_e.λx'_e.loves(z,x')[3]] => null
Searching for valid proofs...
Agenda: [g : j[0], (h ⊸ h) : λy_e.dog(y)[1], {h} : y'[4], {i} : z'[5], (Y[i] ⊸ (h[h] ⊸ Y)) : λt_t.λs_t.λQ_<e,t>.λP_<e,t>.∀x[P(x) → Q(x)](λy'_e.s)(λz'_e.t)[2], (h ⊸ (h ⊸ f)) : λz_e.λx'_e.loves(z,x')[3]]
Combining premises {h} : y'[4] and (h ⊸ h) : λy_e.dog(y)[1]
--> h{h} : dog(y')[1, 4]
Combining premises (h ⊸ (h ⊸ f)) : λz_e.λx'_e.loves(z,x')[3] and {h} : y'[4]
-->(h ⊸ f){h} : λx'_e.loves(y',x')[3, 4]
prover.ProverException: Meaning side does not match structure of glue side
	at prover.LLProver.combinePremises(LLProver.java:230)
	at prover.LLProver.deduce(LLProver.java:142)
	at Main.searchProof(Main.java:122)
	at Main.initiateDependencyMode(Main.java:89)
	at Main.main(Main.java:44)
Enter sentence to be analyzed or enter 'quit' to exit the program.
```

**Comment by mmessmer** [comment]
This was probably an issue with scope assignment as well. It is resolved now, thanks for noticing.
